### ISSUE TITLE
Centering on regions

### ISSUE THREAD

**Issue by maximromanov** [althurayya/althurayya.github.io#3]
I have added the following vars to each place (below); those that have "yes" in "visual_center" are to be used for centering.

```
        "properties": {
            "althurayyaData" : {
                "visual_center" : "no"
            },
```

**Comment by Masoumeh** [comment]
"Mafaza" and "No region" points seem not to have any. For the other regions it works.

**Comment by maximromanov** [comment]
Btw,  can we remove NoRegion from the list of regions? This is a tag for just a few route points.  Mafaza - I will add one!

**Comment by Masoumeh** [comment]
"NoRegion" doesn't appear on the tab anymore.
But I'm not sure whether that works for any data set to hard code the exclusion of "NoRegion". 
If we are going to do it, we need to document it in the data model and characteristics.

**Comment by maximromanov** [comment]
Good point!
