### ISSUE TITLE
Can't clone on Windows

### ISSUE THREAD

**Issue by pverkind** [althurayya/althurayya.github.io#33]
Hi @Masoumeh, 
I can't clone the repo on Windows, because there is a colon ":" in the name of this file: experimental/Other_Files/http:_leafletjs.com_examples_sample-geojson.js

Would it be possible to remove the colon from the filename? Thanks!

(see https://github.com/git-for-windows/git/issues/2777)

**Comment by Masoumeh** [comment]
Hi @pverkind,
thanks for the message.
I renamed the file.
it should be solved now.

**Comment by pverkind** [comment]
It worked, thanks!
