### ISSUE TITLE
Stamen layer

### ISSUE THREAD

**Issue by maximromanov** [althurayya/althurayya.github.io#5]
1. Adding one more map layer: http://maps.stamen.com/watercolor/#5/35.210/23.467
2. Is there a way to make the gazetteer work offline without maps?

**Comment by Masoumeh** [comment]
1. It looks the same as AMWC. Anyway, it's there now!
2. What do you mean by "without map"?

**Comment by maximromanov** [comment]
1. (wispering) never say that they look the same :)  they do not! 
2. I want to be able to work on the gazetteer while offline - now it is impossible,  since it does not load without the map layer

**Comment by Masoumeh** [comment]
1. Practically!
2. I think, we need to have all the layers downloaded locally and then point to the local path in the code.
   Do you want to change it this way?

**Comment by maximromanov** [comment]
1. not really :) One is a real topographical map reflecting the landscape of more than 2,000 years ago; another --- is just a pretty watercolor picture of a modern (!) map.
2. Downloading these layers is going to be difficult --- I am not sure if that is even possible; besides those are pyramidal TIFs, which are very large is you download the whole thing; I wonder if there is some kind of very schematic (vector?) map layer that we could use for the offline work.
